### ISSUE TITLE
Public Reflector Service Down

### ISSUE THREAD

**Issue by Stang66** [conferencexp/conferencexp#24]
Does anyone know why the reflector service reflector.confxp.pnw-gigapop.net is down? Are there any other reflectors that can be used?

Thank you for the help!

Kimm

**Comment by Stang66** [comment]
It looks like reflector is down again.  This may be related to the previously posted issue of Reflector not restarting after server is rebooted.

**Comment by fvideon** [comment]
That's a mystery to me.  It was up when I looked, and I didn't see any sign of a recent reboot.
